### PR TITLE
Add changeNetwork method

### PR DESCRIPTION
**Pull request by haflinger**
Add a changeNetwork method in PortisProvider to avoid another iframe creation.

### CODE REVIEW

**Comment by itay-portis** [comment]
requires SDK 1.2.18

**Comment by itay-portis** [comment]
@haflinger thanks for the PR!
This feature requires changes in our client side, which is not open source (yet!).
We already implemented it and will publish it soon 🚀

**Comment by itay-portis** [comment]
fixed by #14

**Comment by haflinger** [comment]
Hi @itay-portis.  Do you have a release date ?

**Comment by itay-portis** [comment]
@haflinger we already published it :) 
Please make sure you use the latest Portis SDK.

**Comment by haflinger** [comment]
@itay-portis Perfect ! Just tested and it work well. Thanks !

**Pull request closed without merging**
